services:
  api-gateway:
    container_name: api-gateway
    image: ${IMAGE_REPO}/api-gateway:latest
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - order-service
      - inventory-service
      - shipping-service
      - rabbitmq
    environment:
      - APP_MODE=prod
      - ORDER_SERVICE_URL=http://order-service:8001
      - INVENTORY_SERVICE_URL=http://inventory-service:8002
      - SHIPPING_SERVICE_URL=http://shipping-service:8003

  order-service:
    container_name: order-service
    image: ${IMAGE_REPO}/order-service:latest
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - rmqhost=rabbitmq

  inventory-service:
    container_name: inventory-service
    image: ${IMAGE_REPO}/inventory-service:latest
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - order-service
    environment:
      - AMQP_URL=amqp://root:1234@rabbitmq/

  shipping-service:
    container_name: shipping-service
    image: ${IMAGE_REPO}/shipping-service:latest
    restart: always
    ports:
      - "8003:8003"
    depends_on:
      - order-service
    environment:
      - AMQP_URL=amqp://root:1234@rabbitmq/

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s