[project]
name = "shippingservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "httpx",
    "pydantic_settings",
    "aio-pika>=9.6.2"
]

[dependency-groups]
dev = [
    "fastapi[standard]>=0.136.1",
    "ruff>=0.15.15",
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = [
    "E", "F", "I", "FAST"
]

[tool.ruff.format]
quote-style = "single"