name: CI on Digital Ocean self-hosted runner 

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        
      - name: Run Ruff
        run: uvx ruff check --output-format=github .

  build-and-push:
    needs: lint

    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    strategy:
      max-parallel: 1
      matrix:
        include:
          - service: api-gateway
            directory: ApiGateway
          - service: order-service
            directory: OrderService
          - service: inventory-service
            directory: InventoryService
          - service: shipping-service
            directory: ShippingService

    steps:
      - name: Debug Info
        run: |
          echo "Running on:"
          hostname
          whoami

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login GHCR, Build and Push
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG="ghcr.io/${REPO}/${{ matrix.service }}:latest"

          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker buildx build ./src/${{ matrix.directory }} \
            --tag "$IMAGE_TAG" \
            --push \
            --cache-from "type=gha,scope=${{ matrix.service }}" \
            --cache-to "type=gha,mode=max,scope=${{ matrix.service }}"