name: CI on Digital Ocean self-hosted runner 

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        
      - name: Install Ruff
        run: uv install ruff

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

  build-and-push:
    needs: lint

    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    strategy:
      max-parallel: 1
      matrix:
        include:
          - service: api-gateway
            directory: ApiGateway
          - service: order-service
            directory: OrderService
          - service: inventory-service
            directory: InventoryService
          - service: shipping-service
            directory: ShippingService

    steps:
      - name: Debug Info
        run: |
          echo "Running on:"
          hostname
          whoami

      - name: Prepare Image Metadata
        id: meta
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "image_path=ghcr.io/${REPO}/${{ matrix.service }}" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # docker buildx initialize
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./src/${{ matrix.directory }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}